version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_UPLOAD_SERVICE_URL=http://localhost:8081
      - REACT_APP_DOWNLOAD_SERVICE_URL=http://localhost:8082
    depends_on:
      - upload-service
      - download-service
      
  upload-service:
    build: ./upload-service
    container_name: upload-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - AWS_REGION=eu-west-1
      - S3_BUCKET_VIDEOS=your-video-buckets
      - SQS_VIDEO_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/180294222815/your_sqs_url.fifo
    volumes:
      - ~/.aws:/root/.aws:ro
      
  download-service:
    build: ./download-service
    container_name: download-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - AWS_REGION=eu-west-1
      - S3_BUCKET_MP3S=your-mp3-uckets
    volumes:
      - ~/.aws:/root/.aws:ro
      
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
       - "5000:5000"
    environment:
       - PORT=5000
       - DATABASE_HOST=capstone.c18g4q48md9n.eu-west-1.rds.amazonaws.com
       - DATABASE_NAME=auth
       - DATABASE_USER=root
       - DATABASE_PASSWORD=rootpassword
       - AUTH_TABLE=auth_user
       - JWT_SECRET=your-super-secret-jwt-key-2024!@#$$%^&*()
 
  converter-service:
    build: ./converter-service
    container_name: converter-service
    environment:
      - AWS_REGION=eu-west-1
      - S3_BUCKET_VIDEOS=your-video-buckets
      - S3_BUCKET_MP3S=your-mp3-uckets
      - SQS_VIDEO_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/180294222815/your_sqs_url.fifo
      - SQS_MP3_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/180294222815/mp3_sqs_queue.fifo
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      - upload-service
      - download-service

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - AWS_REGION=eu-west-1
      - SQS_MP3_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/180294222815/mp3_sqs_queue.fifo
      - SNS_TOPIC_ARN=arn:aws:sns:eu-west-1:180294222815:Audio_Update
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      - converter-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - upload-service
      - download-service
      - auth-service
      - converter-service
      - notification-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
 