global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'upload-service'
    static_configs:
      - targets: ['upload-service:8081']

  - job_name: 'download-service'
    static_configs:
      - targets: ['download-service:8082']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5000']

  - job_name: 'converter-service'
    static_configs:
      - targets: ['converter-service:8083']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8080'] 